import type { HubCalendarSpecialDay } from "../types.js";

export const productionHubCalendarSpecialDays: HubCalendarSpecialDay[] = [
  {
    id: "birthday:ayatsuno-yuni",
    kind: "member_birthday",
    title: "아야츠노 유니 생일",
    generationId: "gen1",
    memberId: "ayatsuno-yuni",
    month: 5,
    day: 21,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  },
  {
    id: "birthday:sakihane-huya",
    kind: "member_birthday",
    title: "사키하네 후야 생일",
    generationId: "gen1",
    memberId: "sakihane-huya",
    month: 7,
    day: 7,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  },
  {
    id: "birthday:shirayuki-hina",
    kind: "member_birthday",
    title: "시라유키 히나 생일",
    generationId: "gen2",
    memberId: "shirayuki-hina",
    month: 1,
    day: 5,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  },
  {
    id: "birthday:neneko-mashiro",
    kind: "member_birthday",
    title: "네네코 마시로 생일",
    generationId: "gen2",
    memberId: "neneko-mashiro",
    month: 2,
    day: 22,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  },
  {
    id: "birthday:akane-lize",
    kind: "member_birthday",
    title: "아카네 리제 생일",
    generationId: "gen2",
    memberId: "akane-lize",
    month: 10,
    day: 1,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  },
  {
    id: "birthday:arahashi-tabi",
    kind: "member_birthday",
    title: "아라하시 타비 생일",
    generationId: "gen2",
    memberId: "arahashi-tabi",
    month: 9,
    day: 7,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  },
  {
    id: "birthday:tenko-shibuki",
    kind: "member_birthday",
    title: "텐코 시부키 생일",
    generationId: "gen3",
    memberId: "tenko-shibuki",
    month: 3,
    day: 21,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  },
  {
    id: "birthday:aokumo-rin",
    kind: "member_birthday",
    title: "아오쿠모 린 생일",
    generationId: "gen3",
    memberId: "aokumo-rin",
    month: 5,
    day: 3,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  },
  {
    id: "birthday:hanako-nana",
    kind: "member_birthday",
    title: "하나코 나나 생일",
    generationId: "gen3",
    memberId: "hanako-nana",
    month: 8,
    day: 7,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  },
  {
    id: "birthday:yuzuha-riko",
    kind: "member_birthday",
    title: "유즈하 리코 생일",
    generationId: "gen3",
    memberId: "yuzuha-riko",
    month: 4,
    day: 13,
    activeStatus: "active",
    catalogRole: "member",
    sourceLabel: "카탈로그",
    policyState: "catalog_verified"
  }
];
